## cartridge.properties for cartridge app_composable
#Tue Jun 21 14:53:53 EEST 2016
demandware.cartridges.app_composable.id=app_composable
demandware.cartridges.app_composable.multipleLanguageStorefront=true
