orderlimit.limits=Store BOPIS Max: {0}
orderlimit.message=Store {0} has reached the BOPIS Order Max for the day. BOPIS will resume effective 6am ET.
orderlimit.subject=Store {0} Reached Order Max
orderlimit.title=BOPIS Order Max Reached For Your Store