openapi: 3.0.0
info:
  version: 1.0.0
  title: OOBO endpoints
components:
  securitySchemes:
    ShopperToken:
      type: https
      scheme: bearer
      flows:
          authorizationUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/authorize
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_oobo_rw: OOBO scope
paths:
  /startPCIPalSession:
    post:
      summary: Starts a pcipal session
      operationId: startPCIPalSession
      parameters:
        - in: query
          name: siteId
          required: true
          schema:
            type: string
            minLength: 1
        - in: query
          name: c_agentRole
          required: true
          schema:
            type: string
            minLength: 1
      requestBody:
        content:
            'application/json':
             schema:
      responses:
        "200":
          description: Session established
          content:
            application/json:
              schema:
                type: object
                properties:
                  tier:
                    type: string
                  points:
                    type: integer
        "404":
          description: Error
          content:
            application/json:
              examples:
                not_found:
                  value:
                    {
                      "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/custom-errors/basket-not-found",
                    }
security:
  - ShopperToken: ["c_oobo_rw"]
