'use strict';

/**
 * @module searchSuggestHelpers
 * @namespace searchSuggestHelpers
 */

const SuggestModel = require('dw/suggest/SuggestModel');


/**
 * @function getPopularSearchPhrases
 * @memberof searchSuggestHelpers
 * @description Accepts an existing suggestModel, and returns the collection of popular searches
 * generated by Einstein (for the current site / locale / browser -- provided that they exist)
 * @param {dw.suggest.SuggestModel} suggestModel - Existing suggestModel for the current search.
 * @returns {Object} Popular search metadata and phrases iterator.
 */
function getPopularSearchPhrases (suggestModel) {
    // Retrieve the recent collection of popular search phrases
    var popularSearchPhrases = suggestModel.getPopularSearchPhrases();
    // Were any popular search phrases found?
    if (!popularSearchPhrases) {
        return {
            available: false
        };
    }
    // Otherwise, return the collection of retrieved popular searches
    return {
        available: popularSearchPhrases.hasNext(),
        phrases: popularSearchPhrases
    };
}

/**
 * @function getSearchSuggestions
 * @memberof searchSuggestHelpers
 * Builds search suggestion data for a search phrase.
 *
 * @param {string} searchPhrase - The shopper-entered search phrase.
 * @param {number} maxSuggestions - Maximum number of suggestions to retrieve.
 * @returns {Object|undefined} Suggestion payload.
 */
module.exports = function (searchPhrase, maxSuggestions) {
	var suggestModel = new SuggestModel();
	suggestModel.setSearchPhrase(searchPhrase);
	suggestModel.setMaxSuggestions(maxSuggestions);
	if (!suggestModel) {
		return;
	}

	let popular = getPopularSearchPhrases(suggestModel);

	return {
		popular : popular
	};
};
