multiplegiftcerterror=Sorry! Only {0} Gift Cards can be applied per order at this time. Please start a new order to redeem the rest of your Gift Cards.
giftcert.error.zerovalue=Hmm. The Gift Card entered has no balance. Please try another card.
giftcertvalidpin=Oops! Please enter a valid PIN
giftcertinvalid=You have entered an invalid card number, an invalid PIN, or this gift card may have been deactivated due to a $0 balance.
giftcertamountzero=You Got It!
invalidcreditcard=Your credit card could not be processed. Please review your payment method information or try another card.
invalidcreditcardJSON={"page":"billing", "data": { "banner" : "Your credit card could not be processed. Please review your payment method information or try another card." }}
cardnotproccessed = Your credit card could not be processed. Please review your payment method information or try another card.
invalidshipment = There was an issue placing your order. Please review your shipping details or update your address.
defaultcarderror = Heads up! Since you selected Scent-Scription, you need to set a default card in your Account settings to continue.
hazmatItemInvalidAddress = Item(s) in your bag cannot be shipped due to restrictions to the provided address. Please update your bag.