##############################################
# ISML Directory: cart
##############################################
cartcouponinvalid=Your shopping cart contains a promo code that is invalid at this time. Please remove it before proceeding to checkout.
taxinvalid=An error has occurred calculating taxes for one or more products in your cart.
zeroordererror=Sorry! We are currently unable to process $0 orders online. Please remove the code or use this coupon at your local store.
items.zerototal=Sorry! We are currently unable to process $0 orders online. Please remove the code or use this coupon at your local store.
items.selectBopisOffline=In-store pickup is currently unavailable at your selected store. Please see below for details and to choose a different store.
banner.cart.selectBopisOffline = Pickup is currently unavailable at your selected store.
banner.cart.allstoresoffline = Pickup is currently unavailable at all store locations.
banner.cart.bopisstore.orderHold = Typically ready in 4 hours.
banner.cart.bopisstore.unavailable = Pickup is currently unavailable at your store.
limitedQuantity=Oops! Some of the items in your bag have low inventory or are out of stock, Please check below for details.
itemsmerged=Sorry! We have combined your items into a single delivery method due to stock limitations online or in-store. You can now complete your order.
itemsmergedqty=Sorry! The number of products you\u2019ve selected is unavailable for selected delivery method. We\u2019ve adjusted the delivery method and quantity for you.
items.unavailable=Some of the items in your bag have low inventory or are unavailable. Please check below for details.
limitedQuantity=Oops! Some of the items in your bag have low inventory or are out of stock, Please check below for details.
approachingpromo.purchase.message=Purchase {0} more and receive {1}
approachingpromo.purchase.shipping.message=You\u2019re {0} away from {1}.
approachingpromo.purchase=Purchase
approachingpromo.more=more
approachingpromo.receive=and receive
bogopromo=You\u2019ll get {0} item(s) for FREE!
ordergrooverestriction=You must <span class="sign-in-modal">sign in</span> or <span class="create-an-account" >create an account</span> to purchase Scent-scription orders.
paypal.zeroordermsg=The amount to be charged is zero
item.pickup.to.shipment.moved=Sorry! This item is currently unavailable for pickup at this store. We\u2019ve added it for shipping instead. If you still want to pick it up in store, please <a/>.
item.shipment.to.pickup.moved=Sorry! This item is out of stock online. We've added it for pickup instead.
item.purchaselimit.overindividuallimit=You've reached the order limit for this item.


items.unavailableCount={0} of your items {1} unavailable. Please check below for details.
items.allocationUnavailable=unavailable. Please check below for details.
item.outofstock.online_pickup=Out of stock. Please remove before checkout.
item.outofstock.online=Out of stock online. Switch to pickup.
item.outofstock.pickup=Out of stock for pickup. {0} or switch to shipping.
item.outofstock.pickup.nostore=Out of stock for pickup. Switch to shipping.
item.unavailable.pickup.bopisoff=Unavailable for pickup. Switch to shipping.
item.unavailable.pickup.storeoff=Unavailable for pickup. {0} or switch to shipping.
cart.LOYALTY_TYPE_GUEST=Looks like you\u2019ve entered a Reward Code. Please log in and use the "Reward Codes" section to redeem your reward.
cart.LOYALTY_TYPE_REGISTERED=Looks like you\u2019ve entered a Reward Code. Please use the "Reward Codes" section to redeem your reward.
cart.LOYALTY_TYPE_REGISTERED_NOT_MEMBER=Looks like you\u2019ve entered a Reward Code. Please log in and use the "Reward Codes" section to redeem your reward.

#couponBannerMsg#
BOPISONLY_COUPON_NO_STORESELECTED = To activate the in-store pickup promotion, set a store location and select Pick Up in Store for all items in your bag.
NOT_MIXED_BOPIS_COUPON = To activate the in-store pickup promotion, select Pick Up in Store for all items in your bag.
NOT_MIXED_STH_COUPON = To activate the shipping-only promotion, select Ship It for all items in your bag.
MIXEDBAG_BOPIS = To activate the in-store pickup promotion, select Pick Up in Store for all items in your bag.
MIXEDBAG_STH = To activate the shipping-only promotion, select Ship It for all items in your bag.
coupons.couponFieldHidden = Promo codes cannot be used during major sales events and have been removed.
