summary.youritems=Your Items
email.order.qty=QTY
global.free=Free
cart.giftcertdelivery=E-Gift Cards will be delivered by email.
global.giftcards=Gift Cards
global.amt=Amt
global.to=To
global.from=From
summary.giftmessage=Gift Message
checkoutprogressindicator.shipping=Shipping
summary.shipto=Ship To
country.the.unitedstates=The United States
country.unitedstates=United States
country.germany=Germany
country.canada=Canada
country.japan=Japan
country.france=France
country.italy=Italy
country.china=China
country.unitedkingdom=United Kingdom
country.us=United States
country.de=Germany
country.ca=Canada
country.jp=Japan
country.fr=France
country.it=Italy
country.cn=China
country.gb=United Kingdom
country.uk=United Kingdom
country.US=United States
country.CA=Canada
country.AG=Antigua And Barbuda
country.AR=Argentina
country.AW=Aruba
country.AU=Australia
country.AT=Austria
country.BS=Bahamas
country.BD=Bangladesh
country.BY=Belarus
country.BE=Belgium
country.BM=Bermuda
country.BA=Bosnia and Herzegovina
country.BR=Brazil
country.BG=Bulgaria
country.KY=Cayman Islands
country.CL=Chile
country.CN=China
country.CO=Colombia
country.CR=Costa Rica
country.HR=Croatia
country.CY=Cyprus
country.CZ=Czech Republic
country.DK=Denmark
country.DO=Dominican Republic
country.EC=Ecuador
country.EG=Egypt
country.SV=El Salvador
country.FI=Finland
country.FR=France
country.GF=French Guiana
country.DE=Germany
country.GR=Greece
country.GT=Guatemala
country.VA=Holy See (Vatican City State)
country.HN=Honduras
country.HK=Hong Kong
country.HU=Hungary
country.IS=Iceland
country.IN=India
country.ID=Indonesia
country.IE=Ireland
country.IL=Israel
country.IT=Italy
country.JM=Jamaica
country.JP=Japan
country.JO=Jordan
country.LI=Liechtenstein
country.LT=Lithuania
country.LU=Luxembourg
country.MO=Macau
country.MK=Macedonia
country.MG=Madagascar
country.MY=Malaysia
country.MT=Malta
country.MQ=Martinique
country.MX=Mexico
country.MA=Morocco
country.NL=Netherlands
country.AN=Netherlands Antilles
country.NZ=New Zealand
country.NO=Norway
country.PA=Panama
country.PE=Peru
country.PH=Philippines
country.PL=Poland
country.PT=Portugal
country.RO=Romania
country.RU=Russian Federation
country.SA=Saudi Arabia
country.SG=Singapore
country.SK=Slovakia
country.SI=Slovenia
country.ZA=South Africa
country.KR=South Korea
country.ES=Spain
country.LK=Sri Lanka
country.SE=Sweden
country.CH=Switzerland
country.TW=Taiwan
country.TH=Thailand
country.TT=Trinidad And Tobago
country.TR=Turkey
country.TC=Turks And Caicos Islands
country.AE=United Arab Emirates
country.UK=United Kingdom
country.VE=Venezuela
country.VN=Vietnam
country.VG=Virgin Islands (British)
singleshipping.shippingmethodheader=Shipping Method
email.estimateddelivery=Estimated Delivery
checkoutprogressindicator.billing=Billing
summary.billto=Bill To
order.orderdetails.paymentmethod=Payment Method
order.orderdetails.paymentmethods=Payment Methods
global.estimatedtotal=Order Total
order.ordersummary.orderdiscount=Order Discount
order.ordersummary.subtotal=Merchandise Subtotal
order.ordersummary.giftbox=Gift Box
order.ordersummary.ordershipping.edit=Edit
global.symbol.dash= -
summary.shipping=Shipping
order.ordersummary.ordershippingdiscount=Shipping Discount
canadatax.gsthst=GST/HST
canadatax.duty=Estimates Duties
canadatax.gst=Goods and Services Tax (GST)
canadatax.pst=Provincial Sales Tax (PST)
canadatax.hst=Harmonized Sales Tax (HST)
canadatax.qst=Quebec Sales Tax (QST)
order.ordersummary.ordertax=Sales Tax
summary.paymentsummary=Payment Summary
summary.orderpickup=Order Pickup
summary.free=FREE
global.giftcard=Gift Card
email.orderconfirm.shippinginfo=Shipping Information
email.orderconfirm.pickupinfo=Pickup Information
summary.ordertotalUSD=Order Total (USD)
product.label=Go to Product: {0}
global.itemno=Item No:
global.price=Price
global.edit=Edit
product.display.surcharge=Shipping surcharge
global.giftcertificate=Gift Certificate
product.pricing.noprice=N/A
product.pricing.payless=Buy more, pay less!
product.pricing.paymore=Buy more, pay a lot less!
product.pricing.items=items
product.pricing.more=or more
product.pricing.off=% off
global.product.pricing.now=Now
product.error.lowinv.cart=Only <b>{0}</b> in stock. Quantity has been adjusted to reflect the number of products available.
product.error.lowinventory.cart=Sorry! The number of products you\u2019ve selected is unavailable online. We\u2019ve adjusted the quantity for you.
bopis.global.instock=Available
global.remainingnotavailable=This item is currently out of stock. Please remove the item before checkout.
bopis.global.instock=Available
global.quantityinstock={0} Item(s) in Stock
global.allpreorder=Pre-Order
global.remainingpreorder=The remaining items are available for pre-order.
global.quantitypreorder={0} item(s) are available for pre-order.
global.inStockDate=The expected in-stock date is {0}.
global.quantitybackorder=Back order {0} item(s)
global.allbackorder=Back Order
global.remainingbackorder=The remaining items are available on back order.
global.soldout=Sorry, we\'re sold out. Item removed from your bag.
global.remainingnotavailable=The remaining items are currently not available. Please adjust the quantity.

