order.orderconfirmation-email.001=Confirmation of Your Order
confirmation.orderemail.subject=we received your order ({0})!
email.ordernumber=Order Number
email.orderdate=Order Date
account.passwordemail.hi=Hi
email.estimateddelivery=Estimated Delivery
email.order.progress=Progress
email.order.vieworderstatus=View Order Status
email.orderconfirm.message2=Your order can\u2019t be changed at this time.
email.fromname=Bath & Body Works <{0}>
email.bopis.orderconfirm.thankyou=Thanks for your order!
summary.youritems=Your Items
summary.ordertotalUSD=Order Total (USD)
email.order.qty=QTY
global.free=Free
cart.giftcertdelivery=E-Gift Cards will be delivered by email.
global.giftcard=Gift Card
global.amt=Amt
global.to=To
global.from=From
email.orderconfirm.shippinginfo=Shipping Information
email.orderconfirm.pickupinfo=Pickup Information
summary.giftmessage=Gift Message
checkoutprogressindicator.billing=Billing
summary.billto=Bill To
order.orderdetails.paymentmethod=Payment Method
order.orderdetails.paymentmethods=Payment Methods
