paymentInstruments.failedremoval=Card could not be removed!
paymentInstruments.removedcard=Card has been removed.
paymentInstruments.editcardmessage=Got it! We\u2019ve updated your card.
paymentInstruments.greeting=Hi {0},

paymentInstruments.email.addcardsubject=Your new card has been added.
paymentInstruments.email.addcardmessage=You\u2019ve successfully added a new card to your account.

paymentInstruments.email.deletecardsubject=Your card has been removed.
paymentInstruments.email.deletecardmessage=You\u2019ve successfully removed a card from your account.

paymentInstruments.email.editcardsubject=Your card has been updated.
paymentInstruments.email.editcardmessage=Got it! We\u2019ve updated your card.

paymentInstruments.email.defaultcardsubject=Your default card has been updated.
paymentInstruments.email.defaultcardmessage=You\u2019ve successfully updated the default card on your account.

paymentInstruments.email.message1=Didn\u2019t mean to do that or need to make changes? No problem! To update your payment information, visit My Payment Methods in <a href="{0}">My Account</a>.
paymentInstruments.email.message2=Have questions or need assistance?
paymentInstruments.email.message3=We\u2019re here to help. Visit our <a href="{0}">FAQS</a> or contact <a href="{1}">Customer Care</a>.