failed=There was an issue processing your order at this time. Please try again or choose a different payment method.
radial-fail=There was an issue processing your order at this time. Please try again or choose a different payment method.
invalid-shipping-country=Please update your PayPal information. Make sure your shipping address is located within the United States, Puerto Rico, or U.S. territories.
invalid-state-billing=Billing state is missing. Please update and try again.
invalid-state-shipping=Shipping state is missing. Please update and try again.
invalid-street=Shipping address is invalid. Please update and try again.
invlaid-name=Special characters aren’t allowed in the first or last name. Please update and try again.
invalid-zip-code-shipping=Shipping ZIP code is invalid. Please update and try again.
invalid-zip-code-billing = Billing ZIP code is invalid. Please update and try again.
invalid-city-billing= Billing city is missing. Please update and try again.
shipping-restrictions=Item(s) in your bag cannot be shipped due to to restrictions to the provided address. Please update your bag.
invalid-city-shipping= Shipping city is missing. Please update and try again.
invalid-province-address=Please update your shipping or billing address. The postal code must match the selected province.