openapi: 3.0.0
info:
  version: 1.0.0
  title: Radial JWT token for iframe
components:
  securitySchemes:
    ShopperToken:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/authorize
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_radialToken_r: Radial JWT token for iframe
        clientCredentials:
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_radialToken_r: Radial JWT token for iframe
paths:
  /iframeToken:
    get:
      summary: Radial JWT token API
      operationId: iframeToken
      parameters:
        - in: query
          name: siteId
          required: true
          schema:
            type: string
            minLength: 1
      responses:
        "200":
          description: JWT token for iframe
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_in:
                    type: number
                  token_type:
                    type: string

        '404':
          description: Radial JWT token failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                  errorMessage:
                    type: string
                  errorDescription:
                    type: string
                  error:
                    type: string
security:
  - ShopperToken:
      - c_radialToken_r
