openapi: 3.0.0
info:
  version: 1.0.0
  title: Process an order
components:
  securitySchemes:
    ShopperToken:
      type: https
      scheme: bearer
      flows:
          authorizationUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/authorize
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_getbasket_rw:
paths:
  /processOrder:
    post:
      summary: Process an order
      operationId: processOrder
      parameters:
        - in: query
          name: siteId
          required: true
          schema:
            type: string
            minLength: 1
      requestBody:
        content:
            'application/json':
             schema:
              type: object
              required:
                - c_orderNumber
                - c_orderToken
              properties:
               c_orderNumber:
                type: string
                minimum: 1
               c_orderToken:
                type: string
                minimum: 1
      responses:
        "200":
          description: Order Processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  tier:
                    type: string
                  points:
                    type: integer
        "404":
          description: Order failed to process
          content:
            application/json:
              examples:
                not_found:
                  value:
                    {
                      "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/custom-errors/basket-not-found",
                    }
security:
  - ShopperToken: ["c_getbasket_rw"]
