openapi: 3.0.0
info:
  version: 1.0.1
  title: Custom products availability API
components:
  securitySchemes:
    ShopperToken:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/authorize
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_productsAvailability_r: Custom products availability API
        clientCredentials:
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_productsAvailability_r: Custom products availability API
paths:
  /productsAvailability:
    get:
      summary: Get products availability for a given list of products
      operationId: productsAvailability
      parameters:
        - in: query
          name: siteId
          required: true
          schema:
            type: string
            minLength: 1
        - in: query
          name: c_storeId
          required: false
          schema:
            type: string
            minLength: 1
        - in: query
          name: c_productIds
          required: true
          schema:
            type: string
            minLength: 1
      responses:
        "200":
          description: Get products availability for a given list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: string
                  availableInStore:
                    type: boolean
        "404":
          description: Shows that one or more content products are not found
          content:
            application/json:
              examples:
                not_found:
                  value:
                    {
                      "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/custom-errors/customer-not-found",
                    }
security:
  - ShopperToken: ["c_productsAvailability_r"]