openapi: 3.0.0
info:
  version: "1.0.1"
  title: Custom SMS API
components:
  securitySchemes:
    ShopperToken:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/authorize
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_sms_r: Custom SMS API
        clientCredentials:
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_sms_r: Custom SMS API
paths:
  /marketingOptin:
    post:
      summary: Custom SMS API
      operationId: marketingOptin
      parameters:
        - in: path
          name: apiName
          required: true
          schema:
            type: string
        - in: query
          name: siteId
          required: true
          schema:
            type: string
            minLength: 1
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              required:
              - c_phone
              - c_email
              properties:
                c_phone:
                  type: string
                  minimum: 1
                  maximum: 15
                c_email:
                  type: string
                  minimum: 1
                  maximum: 320
      responses:
        "200":
          description: Custom SMS API
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        "404":
          description: Issue with SMS Marketing subscription registration
          content:
            application/json:
              examples:
                not_found:
                  value: '{"type": "https://api.commercecloud.salesforce.com/documentation/error/v1/custom-errors/request-error"}'
security:
  - ShopperToken: ["c_sms_r"]
