openapi: 3.0.0
info:
  version: 1.0.1
  title: Reset Password Success API
components:
  securitySchemes:
    ShopperToken:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/authorize
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_resetSuccessUpdate_r: reset success
        clientCredentials:
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_resetSuccessUpdate_r: reset success
paths:
  /resetSuccess:
    post:
      summary: Reset Password Success API
      operationId: resetSuccess
      parameters:
        - in: query
          name: c_id
          required: false
          schema:
            type: string
            minLength: 1
        - in: query
          name: c_emailToken
          required: false
          schema:
            type: string
            minLength: 1
        - in: query
          name: siteId
          required: true
          schema:
            type: string
            minLength: 1
      responses:
        "200":
          description: Reset Password Success API
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Reset Password Success API
          content:
            application/json:
              examples:
                validation_error:
                  value:
                    {
                      "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/custom-errors/request-error",
                      "message": "Bad Request"
                    }
        "500":
          description: Server issue
          content:
            application/json:
              examples:
                validation_error:
                  value:
                    {
                      "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/custom-errors/server-error",
                      "message": "Server issue"
                    }
security:
  - ShopperToken: ["c_resetSuccessUpdate_r"]
